name = "AutoHist"
uuid = "0bf0ee65-3559-4d1e-a282-1b0e88839781"
authors = ["Oskar HÃ¸gberg Simensen"]
version = "1.0.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
AutoHistMakieExt = "Makie"
AutoHistPlotsExt = "Plots"

[compat]
CairoMakie = "v0.15.0"
Distributions = "v0.25.0"
FFTW = "v1.0.0"
Makie = "v0.24.0"
Plots = "v1.0.0"
SpecialFunctions = "v2.0.0"
Statistics = "v1.0.0"
StatsAPI = "v1.0.0"
StatsBase = "v0.34.0"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots", "Makie", "CairoMakie"]
